#************************************************
#**********  DB Information *********************
#UBI PROD
DriverClass=oracle.jdbc.driver.OracleDriver
Url=jdbc:oracle:thin:@172.27.130.42:1529:FTRADE
UserName=UBZONE
Password=Ubzo#2022


#UBI UAT
#DriverClass=oracle.jdbc.driver.OracleDriver
#Url=jdbc:oracle:thin:@10.128.230.200:1529:FTRADE
#UserName=UBZONE
#Password=Cisco123









