package in.co.forwardcontract.utility;

import in.co.forwardcontract.utility.ActionConstants;

public interface ActionConstantsQuery extends ActionConstants {
  public static final String isValidCurrency = "select COUNT(1) from c8pf where TRIM(C8CCY)=?";
  
  public static final String isValidCustomer = "select COUNT(1) from GFPF  WHERE TRIM(GFCPNC) = ?";
  
  public static final String CUSTOMER_LIST_QUERY = "select GFCUS1,GFCUN,GFCPNC from GFPF order by GFCUS1";
  
  public static final String CUS_ID_FILTER_QUERY = "select GFCUS1 AS CIFID,GFCUN AS CUSTOMER from GFPF ";
  
  public static final String ACCOUNT_LIST_QUERY = "SELECT BO_ACCTNO,ACC_TYPE,BRCH_MNM,CUS_MNM,SHORTNAME,CURRENCY FROM ACCOUNT WHERE TRIM(CUS_MNM) IS NOT NULL AND TRIM(BO_ACCTNO) IS NOT NULL AND CURRENCY = 'INR' ORDER BY CUS_MNM,BO_ACCTNO,ACC_TYPE ";
  
  public static final String ACCOUNT_FILTER_QUERY = "SELECT BO_ACCTNO,ACC_TYPE,BRCH_MNM,CUS_MNM,SHORTNAME,CURRENCY FROM ACCOUNT WHERE  CURRENCY = 'INR'";
  
  public static final String BRANCH_LIST_QUERY = "SELECT CABRNM,FULLNAME FROM CAPF ORDER BY CABRNM";
  
  public static final String BRANCH_FILTER_QUERY = "SELECT CABRNM,FULLNAME FROM CAPF ";
  
  public static final String CURRENCY_LIST_QUERY = "SELECT C8CCY,C8CUR FROM C8PF ORDER BY C8CCY";
  
  public static final String CURRENCY_FILTER_QUERY = "SELECT C8CCY,C8CUR FROM C8PF ";
  
  public static final String FWC_LIST_QUERY_TO_CANCEL = "SELECT ID,CATEGORY,FWC_CONTRACT_NO,SUB_PRODUCT,CIF_ID,BRANCH,CATEGORY FROM CUSTOM_FWC_DETAILS WHERE FWC_CONTRACT_NO IS NOT NULL AND STATUS='APPROVED' AND CATEGORY ='FWCBOOK' ORDER BY ID DESC ";
  
  public static final String FWC_LIST_FILTER_QUERY_TO_CANCEL = "SELECT ID,CATEGORY,FWC_CONTRACT_NO,SUB_PRODUCT,CIF_ID,BRANCH,CATEGORY FROM CUSTOM_FWC_DETAILS WHERE FWC_CONTRACT_NO IS NOT NULL AND STATUS='APPROVED' AND CATEGORY ='FWCBOOK' ";
  
  public static final String INSERT_FWC_BOOKING_DTLS = "INSERT INTO CUSTOM_FWC_DETAILS(CATEGORY,SUB_PRODUCT,CIF_ID,BRANCH,ACCT_NUMBER,DEAL_CCY, \tBOOKING_DATE,FWC_AMOUNT,TO_CCY_AMT,DEAL_VALID_FROM,DEAL_VALID_TO,TREASURY_REF_NO,TREASURY_RATE,OUTSTANDING_AMT,LIMIT_ID,WITHOUT_LIMIT, \tAVAILABLE_LIMIT,WASH_RATE,LEI_NUMBER,PL_AMOUNT,CHARGE_AMOUNT,GST_AMOUNT,INSTRUCTIONS,MARGIN,STATUS,INPUT_BY,INPUT_TIMESTAMP,LAST_ACTION,FWC_CONTRACT_NO) \tVALUES(?,?,?,?,?,?,TO_DATE(?,'dd/mm/yyyy'),?,?,TO_DATE(?,'dd/mm/yyyy'),TO_DATE(?,'dd/mm/yyyy'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSTIMESTAMP,?,?) ";
  
  public static final String UPDATE_FWC_BOOKING_DTLS = "UPDATE CUSTOM_FWC_DETAILS SET SUB_PRODUCT=?,BRANCH=?,ACCT_NUMBER=?,DEAL_CCY=?,BOOKING_DATE=TO_DATE(?,'dd/mm/yyyy'),  FWC_AMOUNT=?,TO_CCY_AMT=?,DEAL_VALID_FROM=TO_DATE(?,'dd/mm/yyyy'),DEAL_VALID_TO=TO_DATE(?,'dd/mm/yyyy') ,TREASURY_REF_NO=?,TREASURY_RATE=?,OUTSTANDING_AMT=?,LIMIT_ID=?,WITHOUT_LIMIT=?,AVAILABLE_LIMIT=?,WASH_RATE=?,LEI_NUMBER=?,  PL_AMOUNT=?,CHARGE_AMOUNT=?,GST_AMOUNT=?,INSTRUCTIONS=?,MARGIN=?,STATUS=?,MODIFIED_BY=?,MODIFIED_TIMESTAMP=SYSTIMESTAMP,LAST_ACTION=? WHERE CATEGORY=? AND FWC_CONTRACT_NO=? ";
  
  public static final String UPDATE_FWC_CANCEL_DTLS = "UPDATE CUSTOM_FWC_DETAILS SET SUB_PRODUCT=?,BRANCH=?,ACCT_NUMBER=?,DEAL_CCY=?,BOOKING_DATE=TO_DATE(?,'dd/mm/yyyy'),  FWC_AMOUNT=?,TO_CCY_AMT=?,DEAL_VALID_FROM=TO_DATE(?,'dd/mm/yyyy'),DEAL_VALID_TO=TO_DATE(?,'dd/mm/yyyy') ,TREASURY_REF_NO=?,TREASURY_RATE=?,OUTSTANDING_AMT=?,LIMIT_ID=?,WITHOUT_LIMIT=?,AVAILABLE_LIMIT=?,WASH_RATE=?,LEI_NUMBER=?,  PL_AMOUNT=?,CHARGE_AMOUNT=?,GST_AMOUNT=?,INSTRUCTIONS=?,MARGIN=?,STATUS=?,MODIFIED_BY=?,MODIFIED_TIMESTAMP=SYSTIMESTAMP,LAST_ACTION=?,CANCELLATION_AMOUNT=?,TRANS_ID=?,TRANS_DATE=?,BOOKING_RATE=? WHERE CATEGORY=? AND FWC_CONTRACT_NO=? ";
  
  public static final String INSERT_FWC_CANCEL_DTLS = "INSERT INTO CUSTOM_FWC_DETAILS(CATEGORY,SUB_PRODUCT,CIF_ID,BRANCH,ACCT_NUMBER,DEAL_CCY, \tBOOKING_DATE,FWC_AMOUNT,TO_CCY_AMT,DEAL_VALID_FROM,DEAL_VALID_TO,TREASURY_REF_NO,TREASURY_RATE,OUTSTANDING_AMT,LIMIT_ID,WITHOUT_LIMIT, \tAVAILABLE_LIMIT,WASH_RATE,LEI_NUMBER,PL_AMOUNT,CHARGE_AMOUNT,GST_AMOUNT,INSTRUCTIONS,MARGIN,STATUS,INPUT_BY,INPUT_TIMESTAMP,LAST_ACTION,FWC_CONTRACT_NO,CANCELLATION_AMOUNT,TRANS_ID, TRANS_DATE, BOOKING_RATE)\tVALUES(?,?,?,?,?,?,TO_DATE(?,'dd/mm/yyyy'),?,?,TO_DATE(?,'dd/mm/yyyy'),TO_DATE(?,'dd/mm/yyyy'),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSTIMESTAMP,?,?,?,?,?,?) ";
  
  public static final String FETCH_FWC_CONTRACT_DTLS = "SELECT ID,CATEGORY,FWC_CONTRACT_NO,SUB_PRODUCT,CIF_ID,BRANCH,ACCT_NUMBER,DEAL_CCY,FWC_AMOUNT,TO_CHAR(TO_DATE(BOOKING_DATE,'DD/MM/YY'),'dd/mm/YYYY') AS BOOKING_DATE,TO_CCY_AMT,TO_CHAR(TO_DATE(DEAL_VALID_FROM,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_FROM,TO_CHAR(TO_DATE(DEAL_VALID_TO,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_TO,TREASURY_REF_NO,TREASURY_RATE,OUTSTANDING_AMT,STATUS FROM CUSTOM_FWC_DETAILS WHERE FWC_CONTRACT_NO IS NOT NULL ";
  
  public static final String FETCH_ALL_FWC_DTLS = "SELECT FWC.ID AS ID,FWC.CATEGORY AS CATEGORY,FWC.FWC_CONTRACT_NO AS FWC_CONTRACT_NO,FWC.SUB_PRODUCT AS SUB_PRODUCT,FWC.CIF_ID AS CIF_ID,FWC.BRANCH AS BRANCH,FWC.ACCT_NUMBER AS ACCT_NUMBER,FWC.DEAL_CCY AS DEAL_CCY, FWC.FWC_AMOUNT AS FWC_AMOUNT,TO_CHAR(TO_DATE(FWC.BOOKING_DATE,'DD/MM/YY'),'dd/mm/YYYY') AS BOOKING_DATE,FWC.TO_CCY_AMT AS TO_CCY_AMT, TO_CHAR(TO_DATE(FWC.DEAL_VALID_FROM,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_FROM,TO_CHAR(TO_DATE(FWC.DEAL_VALID_TO,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_TO, FWC.TREASURY_REF_NO AS TREASURY_REF_NO,FWC.TREASURY_RATE AS TREASURY_RATE,NVL(REGEXP_REPLACE(FWC.FWC_AMOUNT,'[^0-9]+','')-TRSY.DEAL_AMOUNT ,REGEXP_REPLACE(FWC.FWC_AMOUNT,'[^0-9]+',''))||' '||FWC.DEAL_CCY AS OUTSTANDING_AMT,FWC.STATUS AS STATUS FROM CUSTOM_FWC_DETAILS FWC,CUSTOM_TREASURY_INSERT_TBL TRSY WHERE FWC_CONTRACT_NO IS NOT NULL AND FWC.FWC_CONTRACT_NO=TRSY.FWC_REF_NUM(+) AND FWC.CATEGORY=TRSY.HOST_DEAL_CATEGORY(+) ";
  
  public static final String FETCH_FWC_ENQUIRY_DTLS = "SELECT * FROM CUSTOM_FWC_ENQ_DETAILS_VIEW WHERE FWC_REF_NUM IS NOT NULL AND COUNTERPARTY_STRING IS NOT NULL ";
  
  public static final String APPROVE_FWC = "UPDATE CUSTOM_FWC_DETAILS SET STATUS =?,CHECKER_ACTION_BY=?,CHECKER_ACTION_TIMESTAMP=SYSTIMESTAMP,REMARKS=?,LAST_ACTION=?,LIMIT_SERIAL_NUM=?,POSTING_TRAN_ID=? WHERE CATEGORY=? AND FWC_CONTRACT_NO=? AND ID=? ";
  
  public static final String REJECT_FWC = "UPDATE CUSTOM_FWC_DETAILS SET STATUS =?,CHECKER_ACTION_BY=?,CHECKER_ACTION_TIMESTAMP=SYSTIMESTAMP,REMARKS=?,LAST_ACTION=?  WHERE CATEGORY=? AND FWC_CONTRACT_NO=? AND ID=? ";
  
  public static final String DELETE_FWC = "UPDATE CUSTOM_FWC_DETAILS SET STATUS =?,CHECKER_ACTION_BY=?,CHECKER_ACTION_TIMESTAMP=SYSTIMESTAMP,REMARKS=?,LAST_ACTION=?  WHERE CATEGORY=? AND FWC_CONTRACT_NO=? AND ID=? ";
  
  public static final String FETCH_SINGLE_FWC = "SELECT ID,CATEGORY,FWC_CONTRACT_NO,SUB_PRODUCT,CIF_ID,BRANCH,ACCT_NUMBER,DEAL_CCY, STATUS,  FWC_AMOUNT,TO_CHAR(TO_DATE(BOOKING_DATE,'DD/MM/YY'),'dd/mm/YYYY') AS BOOKING_DATE,TO_CCY_AMT,TO_CHAR(TO_DATE(DEAL_VALID_FROM,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_FROM,  TO_CHAR(TO_DATE(DEAL_VALID_TO,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_TO,TREASURY_REF_NO,TREASURY_RATE,OUTSTANDING_AMT,LIMIT_ID,WITHOUT_LIMIT,AVAILABLE_LIMIT,WASH_RATE,LEI_NUMBER,  PL_AMOUNT,CHARGE_AMOUNT,GST_AMOUNT,INSTRUCTIONS,MARGIN,REMARKS FROM CUSTOM_FWC_DETAILS WHERE ID=? AND FWC_CONTRACT_NO=? ";
  
  public static final String FETCH_SINGLE_FWC_CANCEL = "SELECT ID,CATEGORY,FWC_CONTRACT_NO,SUB_PRODUCT,CIF_ID,BRANCH,ACCT_NUMBER,DEAL_CCY,  FWC_AMOUNT,TO_CHAR(TO_DATE(BOOKING_DATE,'DD/MM/YY'),'dd/mm/YYYY') AS BOOKING_DATE,TO_CCY_AMT,TO_CHAR(TO_DATE(DEAL_VALID_FROM,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_FROM,  TO_CHAR(TO_DATE(DEAL_VALID_TO,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_TO,TREASURY_REF_NO,TREASURY_RATE,OUTSTANDING_AMT,LIMIT_ID,WITHOUT_LIMIT,AVAILABLE_LIMIT,WASH_RATE,LEI_NUMBER,  PL_AMOUNT,CHARGE_AMOUNT,GST_AMOUNT,INSTRUCTIONS,MARGIN,REMARKS FROM CUSTOM_FWC_DETAILS WHERE FWC_CONTRACT_NO=? AND CATEGORY='FWCBOOK' ";
  
  public static final String FETCH_SINGLE_ENQUIRY_CANCEL = "SELECT ID,CATEGORY,FWC_CONTRACT_NO,SUB_PRODUCT,CIF_ID,BRANCH,ACCT_NUMBER,DEAL_CCY,  FWC_AMOUNT,TO_CHAR(TO_DATE(BOOKING_DATE,'DD/MM/YY'),'dd/mm/YYYY') AS BOOKING_DATE,TO_CCY_AMT,TO_CHAR(TO_DATE(DEAL_VALID_FROM,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_FROM,  TO_CHAR(TO_DATE(DEAL_VALID_TO,'DD/MM/YY'),'dd/mm/YYYY') AS DEAL_VALID_TO,TREASURY_REF_NO,TREASURY_RATE,OUTSTANDING_AMT,LIMIT_ID,WITHOUT_LIMIT,AVAILABLE_LIMIT,WASH_RATE,LEI_NUMBER,  PL_AMOUNT,CHARGE_AMOUNT,GST_AMOUNT,INSTRUCTIONS,MARGIN,REMARKS,CANCELLATION_AMOUNT,TRANS_ID,TRANS_DATE,BOOKING_RATE FROM CUSTOM_FWC_DETAILS WHERE ID=? AND FWC_CONTRACT_NO=? ";
  
  public static final String FWC_GL_ACCT_QUERY = "SELECT TYPE,ACCOUNT_NUMBER,DR_CR_FLAG,DESCRIPTION FROM CUSTOM_FWC_GL_ACCOUNTS WHERE SUBPRODUCT LIKE '%'||?||'%' AND ACCOUNT_NUMBER IN ('4220013000', 'CustomerAccount')";
  
  public static final String FWC_REVERSAL_POSTING_QUERY = "SELECT POSTING_ACCT_NO,DR_CR_FLAG,POSTING_AMOUNT,POSTING_CCY,TO_CHAR(TO_DATE(SYSDATE,'DD/MM/YY'),'dd/mm/YYYY') AS VALUE_DATE,POSTING_DESC FROM CUSTOM_FWC_POSTING WHERE FWC_REFERENCE=?";
  
  public static final String INSERT_POSTING_DTLS = "INSERT INTO CUSTOM_FWC_POSTING(CATEGORY,FWC_REFERENCE,CUSTOMER_ID,DR_CR_FLAG,POSTING_ACCT_NO,POSTING_BRANCH,POSTING_AMOUNT,POSTING_CCY,VALUE_DATE, POSTING_DESC,POSTING_SEQNO, POSTING_TIMESTAMP) VALUES (?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?,SYSTIMESTAMP) ";
  
  public static final String REC_COUNT_CANCEL = "SELECT COUNT(*) AS COUNT FROM CUSTOM_FWC_DETAILS WHERE FWC_CONTRACT_NO=? AND CATEGORY=? AND ID=?";
  
  public static final String FWC_FTI_INSERT_QUERY = "INSERT INTO CUSTOM_TREASURY_INSERT_TBL( FBO_ID_TYPE, FBO_ID_NUM, FBO_ID_VER, HOST_DEAL_CATEGORY, HOST_DEAL_ACTION, HOST_TRAN_DATE, CAPTURE_TIMESTAMP, UPDATE_TIMESTAMP, RECORD_STATUS, ENTRY_USER_ID, ACCEPT_USER_ID, BUY_OR_SELL, VALUE_DATE, DEAL_AMOUNT, DEAL_AMOUNT_CCY, BUY_AMOUNT, BUY_AMOUNT_CCY, SELL_AMOUNT, SELL_AMOUNT_CCY, FWD_CONTRACT_RATE, CONTRACT_RATE, LBS_RATE, INTERNAL_RATE,REFERENCE_NUM, COUNTERPARTY_STRING,START_DATE,END_DATE, SOL_ID, BILL_ID, FWC_REF_NUM, RATE_CODE, DEAL_REF, DEAL_VERSION, ADDITIONAL_TEXT_1, ADDITIONAL_TEXT_2, ADDITIONAL_TEXT_3, ADDITIONAL_TEXT_4, CONSOLIDATE_FLAG, ENTITY_FBO_ID_NUM, ADDITIONAL_TEXT_10) values ('HDEALD', ? , 1, ?, 'ACCEPT', ?, SYSDATE, SYSDATE, ?, ?, 'SYSTEM', ?,  TO_DATE(?,'dd-MM-yy'), ?, ?, ?, ?, ?, ?,  ?, 0, 0,?, ?, ?,TO_DATE(?,'dd-MM-yy'),TO_DATE(?,'dd-MM-yy'), ?, ?, ?, 'TTB',  0, 0, ?, 'FINASTRA', ?, ?, 'Y',1,'Y') ";
  
  public static final String FWC_AVAILABLE_AMT_QUERY = "SELECT TO_CHAR(SUM(CASE WHEN HOST_DEAL_CATEGORY='FXRATE' THEN BUY_AMOUNT  WHEN HOST_DEAL_CATEGORY='FWCBOOK' THEN BUY_AMOUNT \tWHEN HOST_DEAL_CATEGORY='FWCUTIL' THEN -BUY_AMOUNT \tWHEN HOST_DEAL_CATEGORY='FWCCANCEL' THEN -SELL_AMOUNT END)) AS BUY_AMOUNT,  TO_CHAR(SUM(CASE WHEN HOST_DEAL_CATEGORY='FXRATE' THEN SELL_AMOUNT  WHEN HOST_DEAL_CATEGORY='FWCBOOK' THEN SELL_AMOUNT \tWHEN HOST_DEAL_CATEGORY='FWCUTIL' THEN -SELL_AMOUNT \tWHEN HOST_DEAL_CATEGORY='FWCCANCEL' THEN -BUY_AMOUNT END)) AS SELL_AMOUNT FROM CUSTOM_TREASURY_INSERT_TBL  WHERE RECORD_STATUS <>'DELETED' AND COUNTERPARTY_STRING IS NOT NULL AND FWC_REF_NUM IS NOT NULL  AND FWC_REF_NUM=? AND COUNTERPARTY_STRING =?";
  
  public static final String UPDATE_FAILED = "UPDATE CUSTOM_FWC_DETAILS SET STATUS =?,CHECKER_ACTION_BY=?,CHECKER_ACTION_TIMESTAMP=SYSTIMESTAMP,REMARKS=?,LAST_ACTION=? WHERE CATEGORY=? AND FWC_CONTRACT_NO=? AND ID=? ";
  
  public static final String UPDATE_PENDING = "UPDATE CUSTOM_FWC_DETAILS SET STATUS =?,CHECKER_ACTION_BY=?,CHECKER_ACTION_TIMESTAMP=SYSTIMESTAMP,REMARKS=?,LAST_ACTION=? WHERE CATEGORY=? AND FWC_CONTRACT_NO=? AND ID=? ";
  
  public static final String UPDATE_TRAN = "UPDATE CUSTOM_FWC_DETAILS SET TRANS_ID =?,TRANS_DATE=? WHERE CATEGORY=? AND FWC_CONTRACT_NO=? AND ID=?";
}


/* Location:              C:\Users\ditbit435\Downloads\FwdContractProcess_war_080626 (1)\FwdContractProcess.war!\WEB-INF\classes\in\co\forwardcontrac\\utility\ActionConstantsQuery.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */